### ISSUE TITLE
Formalize participants' age to actually allow for other than year units/durations 

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#1633]
ATM it must be in years (according to schema and hardcoded there assumptions), although [text](https://github.com/bids-standard/bids-specification/blob/0dcb141fccec5bbd92e482a071fefba0d0bbfdb1/src/modality-agnostic-files.md?plain=1#L263) suggests differently 

```
If no `units` is provided for age, it will be assumed to be in years relative to date of birth.
```

which was suggested/accepted in code review of #459 but 1. no alternative units are specified (thus unknown/useless) ; 2. such relaxation was not **later** reflected in the schema which now just [hardcode](https://github.com/bids-standard/bids-specification/blob/HEAD/src/schema/objects/columns.yaml#L35) via `unit: years` without alternative unit values provided. (not even sure if we formalize units to be machine readable ATM, e.g. see #1631 to fix some values)

@bids-standard/bep032  is working on  animal ecephys. In "animal world" restriction to age in years is often too restrictive, ambiguous in conversion (# of days in a year changes, # of days in month variable, etc) or not even expressive enough (pre-gestational age etc; let's keep that for a separate issue).  So we need to improve on specification of age by allowing other "units" and also allow for metadata field following some dictionary which would allow specification of the "age reference".  Here is what is done in other standards/uses:

-  NWB uses "age" of "text" type . For DANDI then it allows for treating  [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) values if those are specified, enforced during metadata validation using [nwbinspector](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/checks/nwbfile_metadata.py#L133) . Use of ISO 8601 makes any duration inambigous.

Since we are "unit" oriented ATM, I think the easiest resolution for this aspect would be to just do implement in the schema on what is promised in the text:

- Consider "Units" sidecar file value
- Define explicit "unit" values which would be accepted for age: year, month, day, hour, minute, s, ms

Question to schema folks (@effigies @rwblair @nellh): how difficult would be to generalize current check

```yaml
CheckAge89:
  issue:
    code: AGE_89
    message: .... trimmed...
    level: warning
  selectors:
    - path == 'participants.tsv'
    - columns.age != null
  checks:
    - max(columns.age) < 89
```

to support use of the "Units" in the side car?

**Comment by Remi-Gau** [comment]
Sort of related: 
- https://github.com/bids-standard/bids-specification/issues/1020
- https://github.com/bids-standard/bids-specification/issues/458

**Comment by yarikoptic** [comment]
![image](https://github.com/bids-standard/bids-specification/assets/39889/ea4f3251-8d7b-4ccf-8f82-d00ce18a1ad9)

**Comment by yarikoptic** [comment]
https://giphy.com/gifs/bushes-spicer-correction-COYGe9rZvfiaQ/fullscreen

**Comment by yarikoptic** [comment]
@effigies @rwblair we need to get back to this -- it is crucial for animal research.

My original

- https://github.com/bids-standard/bids-specification/pull/1791

was closed by @rwblair and it was partially addressed (89+ aspect) in

- https://github.com/bids-standard/bids-specification/pull/2162

but overall now we still have it ["hardcoded" as JSON schema record](https://github.com/bids-standard/bids-specification/blob/master/src/schema/objects/columns.yaml#L35)

```yaml
age:
  name: age
  display_name: Subject age
  description: |
    Numeric value in years (float or integer value).

    For privacy purposes, participant ages should be capped at 89.
    Using "89+" for ages above 88 is DEPRECATED.
  definition: {
    "LongName": "Subject age",
    "Description": "Subject age in postnatal years",
    "Format": "number",
    "Units": "year",
    "Maximum": 89,
  }
```

from that read, and IIRC

- this is still hardcoded to "years" in description
- we cannot override in the `participants.json` to be different (what specific values?) unit

Is my observation is correct and we still need to work out a solution or we can overload and thus this issue could be closed???

**Comment by effigies** [comment]
Are you having trouble overriding the definition? I thought this was resolved (at least technically, I think the question of documenting overridable columns is open).

**Comment by yarikoptic** [comment]
Frankly, I am still not sure "how" to override it (just add "Units"? what are permissible values -- see below -- so tools could rely on finding them?)  so it is formally correct (since we can add arbitrary sidecar json fields) and "in effect". But also `description` in the cited definition in both `description` and `definition.Description` says "years" without suggesting it could be overridden.

### How?

Apparently we do have  1 example already:

```
❯ for f in */participants.json; do jq -r .age.Units $f; done | sort | uniq -c | sort -n
      1 month
      9 year
     19 null
     31 years
```

but it is not what it means I guess since it actually is years from what I see:

```
❯ grep -B4 "month" */parti*json
genetics_ukbb/participants.json-{
genetics_ukbb/participants.json-  "age": {
genetics_ukbb/participants.json-    "LongName": "age",
genetics_ukbb/participants.json-    "Description": "age of the participant",
genetics_ukbb/participants.json:    "Units": "month"
❯ head genetics_ukbb/participants.tsv
participant_id	age	sex	group	genetic_id	IDH	BatchID	VariationSetType	Assembly	GeneticDataType
sub-01	48	M	patient	125425	yes	b001	CNV	hg38	SNP_intensity
sub-02	60	M	control	125698	no	b001	CNV	hg38	SNP_intensity
sub-03	72	M	patient	452589	yes	b002	SNV/CNV	hg19/hg38	WES/SNP_intensity
sub-04	84	F	patient	325478	no	b002	CNV	hg38	SNP_intensity
sub-05	89+	M	control	623589	yes	b002	SNV/CNV	hg19/hg38	WES/SNP_intensity
sub-06	89+	F	patient	458712	no	b003	SNV	hg19	WES
sub-07	89+	M	patient	985632	yes	b004	SNV	hg19	WES
sub-08	60	F	control	325687	yes	b004	CNV	hg38	SNP_intensity
sub-09	48	F	patient	753159	no	b005	SNV/CNV	hg19/hg38	WES/SNP_intensity
```

### What?

[Common principle: Units](https://bids-specification.readthedocs.io/en/stable/common-principles.html#units) points to use [SI](https://en.wikipedia.org/wiki/International_System_of_Units) nomenclature, but SI defines only the base AFAIK -- seconds, since "month" and "year" are not even convertable to base unit.  We do not list permitted calendar or other values for age besides stating

> Age SHOULD be given as the number of years since birth at the time of scanning (or first scan in case of multi session datasets). Using higher accuracy (weeks) should in general be avoided due to privacy protection, unless when appropriate given the study goals, for example, when scanning babies.

So that is where we need to expand on that! I think we should explicitly list permittable values and stem them from the used by https://en.wikipedia.org/wiki/ISO_8601 

- second (also SI base)
- minute
- hour
- day
- week
- month (no longer 1-to-1 convertible to SI base without full reference date) 
- year

and here -- plural or singular (see absent consistency in "How"!) ?

FWIW -- IA link to SI brochure talking about durations: https://web.archive.org/web/20180316082544/https://www.bipm.org/en/publications/si-brochure/chapter4.html

**Comment by effigies** [comment]
You override a default definition by defining it in `participants.json`:

```yaml
{
  " age": {
    "Description": "Subject age in days post-partum",
    "Units": "day"
  }
}
```

If that fails, that's a validator bug.

I agree that the SI unit recommendation doesn't fit well here, and we should clear that up, and I'm okay with suggesting units based on the ISO8601 duration designators.
